### ISSUE TITLE
Is it possible to get find_element(s) work with headless option?

### ISSUE THREAD

**Issue by babizo** [sukgu/pyshadow#18]
Hi there,

I tried to use find_element(s) with headless option but it didn't return any results. It works if I comment headless out. What's wrong?

```
from selenium import webdriver
from pyshadow.main import Shadow

options = webdriver.ChromeOptions()
options.add_argument('--headless')
browser = webdriver.Chrome(options=options)
shadow = Shadow(browser)

browser.get('https://www.msn.com/news')

item = shadow.find_element("cs-content-card[heading-level='2']")
```

**Comment by Benjamin-Loison** [comment]
`xvfb-run` is the missing part for headless to work fine.

```bash
xvfb-run python3 test.py 
```
```
Le Parti socialiste annonce la réélection d’Olivier Faure au poste de premier secrétaire Ouest-France
```

Here is a update of your code as currently, with your code (no matter if headless or not):

<details>
<summary>Output:</summary>

```
Traceback (most recent call last):
  File "<tmp 2>", line 11, in <module>
    item = shadow.find_element("cs-content-card[heading-level='2']")
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/benjamin_loison/venv/lib/python3.11/site-packages/multipledispatch/dispatcher.py", line 439, in __call__
    return func(self.obj, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/benjamin_loison/venv/lib/python3.11/site-packages/pyshadow/main.py", line 116, in find_element
    raise ElementNotVisibleException("Element with CSS " + css_selector + " is not present on screen")
selenium.common.exceptions.ElementNotVisibleException: Message: Element with CSS cs-content-card[heading-level="2"] is not present on screen
```
</details>

<details>
<summary>Python script:</summary>

```python
from selenium import webdriver
from pyshadow.main import Shadow
from selenium.webdriver.support.ui import WebDriverWait
from lxml import html

options = webdriver.ChromeOptions()
#options.add_argument('--headless')
browser = webdriver.Chrome(options = options)
wait = WebDriverWait(browser, timeout = 10)
shadow = Shadow(browser)

browser.get('https://www.msn.com/news')

def getElement():
    return shadow.find_element("cs-content-card[heading-level='2']")

def poll(_):
    try:
        getElement()
        return True
    except:
        return False

item = wait.until(poll)
item = getElement()
innerHtml = item.get_attribute('innerHTML')
tree = html.fromstring(innerHtml)
print(tree.text_content().rstrip())

browser.quit()
```
</details>

I verified that `shadow` is necessary.

Note that `browser.implicitly_wait` does not help here.

Maybe related to #1.

Related to [Online_authentication_API/issues/100](https://codeberg.org/Benjamin_Loison/Online_authentication_API/issues/100).
